steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "us-docker.pkg.dev/${PROJECT_ID}/docker-repo/mms-cloud-skeleton:latest"
  - "."
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "us-docker.pkg.dev/${PROJECT_ID}/docker-repo/mms-cloud-skeleton:latest"
images:
- "us-docker.pkg.dev/${PROJECT_ID}/docker-repo/mms-cloud-skeleton:latest"
